// Only for test purpose
export const images = [
	// Images list
	{ id: 0,
		title: 'First image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/600'
	},
	{ id: 1,
		title: 'Second one',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/601'
	},
	{ id: 2,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/601/600' },
	{ id: 3,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/601/601' },
	{ id: 4,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/602' },
	{ id: 5,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/602/600' },
	{ id: 6,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/602/602' },
	{ id: 7,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/603' },
	{ id: 8,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/603/600' },
	{ id: 9,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/603/603' },
	{ id: 10,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/604' },
	{ id: 11,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/604/600' },
	{ id: 12,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/604/604' },
	{ id: 13,
		title: 'Another image',
		subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
		src: 'http://lorempixel.com/600/605' }
]